# OnionOS / Miyoo Mini and Mini Plus (ARMv7 hard-float).
# The device toolchain and the MMIYOO SDL2 SDK are downloaded by the CI
# workflow; using a host ARM compiler produces an incompatible GLIBC binary.
PLATFORM = miyooports
include Makefile.common

LIBS = $(COMMON_LIBS) platforms/sdl2
MIYOO_TOOLCHAIN ?=
MIYOO_SDL2_ROOT ?=
MIYOO_SYSROOT ?= $(MIYOO_TOOLCHAIN)/arm-linux-gnueabihf/libc
CXX = $(MIYOO_TOOLCHAIN)/bin/arm-linux-gnueabihf-g++
STRIP = $(MIYOO_TOOLCHAIN)/bin/arm-linux-gnueabihf-strip

ifeq ($(strip $(MIYOO_TOOLCHAIN)),)
$(error MIYOO_TOOLCHAIN must point to the Miyoo device toolchain)
endif
ifeq ($(strip $(MIYOO_SDL2_ROOT)),)
$(error MIYOO_SDL2_ROOT must point to the MMIYOO SDL2 SDK)
endif

CFLAGS = $(filter-out -flto,$(COMMON_CFLAGS)) $(INCLUDES) \
  --sysroot=$(MIYOO_SYSROOT) -I$(MIYOO_SDL2_ROOT)/include \
  -DMIYOOPORTS_BUILD -DGAMEPAD_SUPPORT -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
XTRA_LIBS = -L$(MIYOO_SDL2_ROOT)/lib -lSDL2 -Wl,--allow-shlib-undefined \
  -lstdc++fs -static-libstdc++ -static-libgcc -ldl -lpthread -lm

object_for = $(BUILD)/obj/$(subst ../,up/,$(basename $(1))).o
OBJECTS := $(foreach source,$(SOURCES),$(call object_for,$(source)))
DEPS := $(OBJECTS:.o=.d)
TARGET = $(BUILD)/choochootracker

define compile_source
$(call object_for,$(1)): $(1) Makefile.miyooports Makefile.common
	@mkdir -p $$(dir $$@)
	@$(CXX) $(CFLAGS) -MMD -MP -c $$< -o $$@
endef

$(foreach source,$(SOURCES),$(eval $(call compile_source,$(source))))
-include $(DEPS)

.PHONY: MiyooPorts MiyooPorts-deploy
MiyooPorts: $(TARGET)

$(TARGET): $(OBJECTS)
	mkdir -p $(BUILD)
	$(CXX) $(CFLAGS) $(OBJECTS) $(XTRA_LIBS) -o $@
	$(STRIP) $@

PACKAGE_ROOT = $(BUILD)/package
PORT_DIR = $(PACKAGE_ROOT)/Roms/PORTS/Games/ChooChooTracker
RELEASE = $(abspath ../releases)/ChooChooTracker-$$(date +%Y-%m-%d)-$(VERSION)-MiyooPorts.zip

MiyooPorts-deploy: MiyooPorts
	rm -rf $(PACKAGE_ROOT)
	mkdir -p $(PORT_DIR)/libs $(PACKAGE_ROOT)/Roms/PORTS/Shortcuts $(PACKAGE_ROOT)/Roms/PORTS/Imgs ../releases
	cp $(TARGET) $(PORT_DIR)/choochootracker
	cp $(MIYOO_SDL2_ROOT)/lib/libSDL2-2.0.so.0 $(MIYOO_SDL2_ROOT)/lib/libneonarmmiyoo.so $(PORT_DIR)/libs/
	cp -r packaging/common/. $(PORT_DIR)/
	cp packaging/miyoo_ports/launch.sh $(PORT_DIR)/
	cp packaging/miyoo_ports/ChooChooTracker.port $(PACKAGE_ROOT)/Roms/PORTS/Shortcuts/
	cp packaging/chipnomad-icon.png $(PACKAGE_ROOT)/Roms/PORTS/Imgs/ChooChooTracker.png
	chmod +x $(TARGET) $(PORT_DIR)/choochootracker $(PORT_DIR)/launch.sh $(PACKAGE_ROOT)/Roms/PORTS/Shortcuts/ChooChooTracker.port
	cd $(PACKAGE_ROOT) && zip -qr $(RELEASE) Roms
	@echo "MiyooPorts package created: $(RELEASE)"
